### ISSUE TITLE
name 'flash' is not defined

### ISSUE THREAD

**Issue by kaichop** [WGLab/PhenCards#121]
The new Docker image shows "name 'flash' is not defined" error when searching clinical notes. @jimhavrilla is there a typo for "flask"?

![image](https://user-images.githubusercontent.com/5926328/227407542-aaee7fe9-d45c-406d-9a51-201fa4086802.png)

**Comment by jimhavrilla** [comment]
no, it should be:
from flask import session, request, Response, abort, flash
flash is an import from flask. it allows one to flash an error message.
https://flask.palletsprojects.com/en/2.2.x/patterns/flashing/#:~:text=Flask%20provides%20a%20really%20simple,layout%20template%20that%20does%20this
.

**Comment by kaichop** [comment]
okay, it is still the same docker instance that I did not change, can you check why flash is not imported now?

![image](https://user-images.githubusercontent.com/5926328/227411456-9a191011-c6ca-4c9b-8278-ebfd8c56784a.png)

**Comment by jimhavrilla** [comment]
The site is working for me

**Comment by kaichop** [comment]
I tried two browsers now and both show same message. Did you check the "patients notes" tab? I can use the "phenotype search" tab just fine.

**Comment by jimhavrilla** [comment]
I see. I don't know why it bugged out before (I just did git checkout
queries.py and rebuilt it) but it is now fixed in prod.
[image: image.png]

**Comment by jimhavrilla** [comment]
I will PR the feature change to master.  PR #122

**Comment by kaichop** [comment]
Okay thank you!

**Comment by jimhavrilla** [comment]
Sure
